# Site
repository: tiennm99/webcv
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Tien Nguyen Minh
title: Senior Software Engineer
email: tiennm99@outlook.com
website: miti99.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: tiennm99
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: miti99
# flickr_username: jekyll
#instagram_username: tiennm99
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: @miti99
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tien and I'm a senior software engineer. I have worked as a java game server developer at ZingPlay Game Studios - VNG Corporation since 2020.

  I am most skilled in: <mark>Java</mark> and <mark>Read Light Novel</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Survival2D - A 2D Battle Royale game
        link: github.com/survival2d
        # link_text: Project Website
        additional_links:
          - title: survival2d.eu.org
            icon: fa fa-gamepad
            url: survival2d.eu.org
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          My Graduation essay.
        description: | # this will include new lines to allow paragraphs
          Because at that time I was working in game area so I want to start a game project. I choose to make a 2D Battle Royale game inprired by surviv.io.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZingPlay Game Studios - VNG Corporation
        link: vng.com.vn
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: July 06 2020 - present
        quote: >
          Join Fresh. Grow Best.
        description: | # this will include new lines to allow paragraphs
          On July 06 2020, I joined Game Studio North - VNG Corporation as a Game Programming Fresher of the VNG Tech Fresher 2020 program.
          
          On January 01 2021, we changed our name to ZingPlay Game Studios.
          
          On October 01 2020, I was promoted to Associate Software Engineer.
          
          On September 26 2021, I was promoted to Software Engineer.
          
          From June 26 2023 util now, I have worked as a Senior Software Engineer.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ho Chi Minh City University of Technology
        caption: 2017
        sub_title: BEng Computer Science
        quote: >
          1 Encouraging Study Scholarship.<br>
          1 Student of 5 merits.
        description: | # this will include new lines to allow paragraphs
          During this time, I improved my knowledge of programming, algorithms, data structures, and other computer science fundamentals. I also learned about create static blog and create blog for me and my team.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game development and software engineering some of my other interests and hobbies are:
      - Try do deploy something on internet: self-hosted services, website, AI,...
      - Help develop open source projects related to Java & game development.
      - Reading light novel, manga. Watching anime.
      - Playing Game

      My dream is to become a magician. 

# Footer
footer_show_references: true
references_title: Made by miti99 with ❤

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
